---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
- name: ubuntu-10.04
- name: centos-6.5
- name: centos-5.10

suites:
- name: alltherubies
  run_list:
  - recipe[ruby_install]
  - recipe[alltherubies]
- name: installation
  run_list:
  - recipe[ruby_install]
